news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: ".field-content a"
      article_body: ".field-name-body"
      article_title: ".pane-content h1"
  elpais:
    url: https://elpais.com
    queries:
        homepage_article_links: ".color_gray_ultra_dark   a"
        article_body: ".article_body"
        article_title: ".basic h1"